# These are supported funding model platforms

# github: YosrBennagra
# patreon: # your_username
# open_collective: # your_username
# ko_fi: # your_username
# tidelift: # npm/package-name
# community_bridge: # project-name
# liberapay: # your_username
# issuehunt: # your_username
# custom: # your_custom_link
